getappmap/appmap-python

- .travis.yml
- pyproject.toml
> Push tagged releases to PyPI

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/_implementation/event.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/test_recording.py
Need to figure out how to fix unit test as elapsed time could be different every time.
> Add elapsed attribute to ReturnEvent.

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/_implementation/event.py
- appmap/_implementation/metadata.py
- appmap/_implementation/utils.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/test_recording.py
> add git to metadata

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/_implementation/generation.py
- appmap/django.py
- appmap/pytest.py
- appmap/test/test_django.py
- pyproject.toml
> Capture SQL queries in django apps

- README.md
- Installation instructions added
- [future work] replaced with [coming soon]
- Minor formatting updates
> Installation instructions added

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/test/data/pytest/test_simple.py
Also, make sure it's an absolute path.
> Set the output directory on startup

- CHANGELOG.md
- README.md
- appmap/_implementation/testing_framework.py
- appmap/pytest.py
- appmap/test/data/pytest/expected.unittest.appmap.json
- appmap/test/data/pytest/test_simple.py
- appmap/test/test_pytest.py
- appmap/test/test_unittest.py
- appmap/unittest.py
> Unittest integration

- CHANGELOG.md
- appmap/__init__.py
- appmap/_implementation/_intflag.py
- appmap/_implementation/configuration.py
- appmap/_implementation/env.py
- appmap/_implementation/event.py
- appmap/_implementation/instrument.py
- appmap/_implementation/recording.py
- appmap/_implementation/testing_framework.py
- appmap/_implementation/utils.py
- appmap/test/appmap_test_base.py
- appmap/test/conftest.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/data/params.py
- appmap/test/data/pytest/expected.appmap.json
- appmap/test/data/pytest/expected.unittest.appmap.json
- appmap/test/data/pytest/test_simple.py
- appmap/test/test_configuration.py
- appmap/test/test_events.py
- appmap/test/test_params.py
- appmap/test/test_recording.py
- conftest.py
Also, make source paths in an AppMap relative to the starting directory.
Fixes #29. Fixes #46.
> Add parameters to call events

- CHANGELOG.md
- README.md
- appmap/__init__.py
- appmap/_implementation/configuration.py
- appmap/_implementation/instrument.py
- appmap/_implementation/recording.py
- appmap/test/appmap_test_base.py
- appmap/test/data/appmap.yml
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/test_recording.py
- pyproject.toml
Fixes #48 .
Reviewing commit-by-commit recommended.
> Support shallow capture, package specs

- .gitmodules
- .travis.yml
- CHANGELOG.md
- README.md
- appmap/_implementation/configuration.py
- appmap/_implementation/event.py
- appmap/_implementation/generation.py
- appmap/_implementation/instrument.py
- appmap/_implementation/recording.py
- appmap/_implementation/utils.py
- appmap/test/conftest.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/test_configuration.py
- appmap/test/test_params.py
- appmap/test/test_recording.py
- appmap/wrapt
- ci/test_install.sh
- pyproject.toml
- pytest.ini
- tox.ini
Module-scoped functions will now show up in appmaps. Fixes #53.
> Instrument module-scoped functions

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/django.py
- appmap/flask.py
- appmap/test/appmap_test_base.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
> Capture HTTP request headers in Django and Flask

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/django.py
- appmap/flask.py
- appmap/test/data/flask/expected.appmap.json
- appmap/test/test_django.py
- appmap/test/test_flask.py
> Http response headers

- CHANGELOG.md
- appmap/flask.py
- appmap/test/data/flask/app.py
- appmap/test/data/remote.appmap.json
- appmap/test/test_django.py
- appmap/test/web_framework.py
Fixes #104.
Also, fix some warnings and failures caused by the release werkzeug 2.0.0.
> Fix formatting of normalized_path_info for flask

- CHANGELOG.md
- appmap/flask.py
- appmap/test/data/remote.appmap.json
- appmap/test/normalize.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
- appmap/test/web_framework.py
> Capture message parameters in flask

- CHANGELOG.md
- appmap/_implementation/env.py
- appmap/_implementation/testing_framework.py
- appmap/test/test_test_frameworks.py
> Limit appmap file name to 255 characters

- CHANGELOG.md
- appmap/django.py
- appmap/test/data/remote.appmap.json
- appmap/test/normalize.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
- appmap/test/web_framework.py
Add normalized_path_info to http_server_request events captured by the
django integration.
> Show normalized_path_info for django

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/_implementation/env.py
- appmap/test/test_configuration.py
- pylintrc
Fixes #55.
Also includes a commit removing pylint exceptions. See the commit message for details.
> Missing config message

- CHANGELOG.md
- README.md
- appmap/django.py
- appmap/test/test_django.py
- appmap/test/web_framework.py
- pyproject.toml
- tox.ini
> Fix Django path normalization, test against Django 2.2

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/_implementation/utils.py
- appmap/_implementation/web_framework.py
- appmap/django.py
- appmap/flask.py
- appmap/http.py
- appmap/test/helpers.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
- appmap/test/test_http.py
- appmap/test/test_metadata.py
- appmap/test/test_sqlalchemy.py
- appmap/test/test_test_frameworks.py
- appmap/test/web_framework.py
> Record template rendering in Django and flask

- CHANGELOG.md
- appmap/django.py
- appmap/test/test_django.py
> Added exception handler for request in the Middleware class of django.

- CHANGELOG.md
- appmap/django.py
- appmap/test/data/django/app/__init__.py
- appmap/test/data/django/app/hello_world.html
- appmap/test/data/django/app/middleware.py
- appmap/test/data/django/app/urls.py
- appmap/test/data/django/appmap.yml
- appmap/test/data/django/test/test_app.py
- appmap/test/test_django.py
- pyproject.toml
Make sure that our django middleware is always present in the stack, even if a test resets it.
Also, factor the django test app out from test_django.py into a separate app.
Fixes #141.
> Make sure the appmap django middleware is always present

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/command/appmap_agent_status.py
- appmap/test/data/appmap-broken.yml
- appmap/test/test_command.py
- appmap/test/test_configuration.py
- pyproject.toml
The subject says it all. :)
Note that discovery of `unittest` tests is not yet supported.
Fixes #143 .
> Add appmap-agent-status command

- appmap/_implementation/configuration.py
- appmap/_implementation/labels.py
- appmap/labeling/__init__.py
- appmap/labeling/yaml.yml
- appmap/test/data/appmap.yml
- appmap/test/data/expected.appmap.json
- pyproject.toml
Just the infrastructure. Specific labels for more libraries to come.
> Preset labels for known library functions

- appmap/labeling/crypto.yml
- appmap/labeling/formats.yml
- appmap/labeling/http.yml
- appmap/labeling/jobs.yml
Adds labels for some popular job queuing and crypto libraries, plus a bit of http.
> Some library labels

- .travis.yml
- appmap/_implementation/recording.py
- pyproject.toml
- tox.ini
> Fix problems mapping with python 3.10

- appmap/_implementation/__init__.py
- appmap/_implementation/configuration.py
- appmap/_implementation/detect_enabled.py
- appmap/_implementation/env.py
- appmap/_implementation/importer.py
- appmap/flask.py
- appmap/test/conftest.py
- appmap/test/test_configuration.py
- appmap/test/test_flask.py
- appmap/test/test_metadata.py
- appmap/test/test_test_frameworks.py
- appmap/test/web_framework.py
- tox.ini
Make sure it instruments application code. There's definitely more testing that could be added here, but [this](https://github.com/getappmap/appmap-python/pull/180/commits/ce0b5239b13608db2874bed175d193267af4ce82#diff-f0da5d71b031834061fcaa37daf4a32c38ab2e6030993abdcbb8e0d7036c22f5R112) is a start.
Fixes getappmap/board#191.
> Fix record-by-defauilt

- .travis.yml
- appmap/_implementation/configuration.py
- appmap/_implementation/env.py
- appmap/test/test_configuration.py
Make sure appmap_dir is set in the generated appmap.yml, the IDE extensions will perform better when it's there.
> fix: set appmap_dir in the default config

- _appmap/configuration.py
- _appmap/generation.py
- _appmap/test/data/django/app/__init__.py
- _appmap/test/test_django.py
- _appmap/test/test_flask.py
- _appmap/test/web_framework.py
- _appmap/web_framework.py
- appmap/command/appmap_agent_status.py
- appmap/django.py
- appmap/flask.py
- appmap/pytest.py
- appmap/unittest.py
- pylintrc
Fixes #209.
Also, clean up some more issues identified by pylint.
This was originally uncovered by a [test in listenbrainz](https://github.com/metabrainz/listenbrainz-server/blob/7712f5edbcd88ec79444d2bf0fbf606a8f0b2366/listenbrainz/tests/integration/test_api.py#L202).
> Improve error handling of application/json requests

- ci/run_tests.sh
- ci/smoketest.sh
- ci/test_poetry.sh
Add a quick and dirty end-to-end smoketest that uses poetry.
Fixes #199 .
> test: add end-to-end smoketest for poetry

- _appmap/configuration.py
- _appmap/env.py
- _appmap/event.py
- _appmap/importer.py
- _appmap/instrument.py
- _appmap/labels.py
- _appmap/metadata.py
- _appmap/recorder.py
- _appmap/recording.py
- _appmap/test/conftest.py
- _appmap/test/test_configuration.py
- _appmap/test/test_generation.py
- _appmap/test/test_http.py
- _appmap/test/test_labels.py
- _appmap/test/test_recording.py
- _appmap/web_framework.py
- appmap/command/appmap_agent_status.py
- appmap/django.py
- appmap/flask.py
- appmap/labeling/__init__.py
- appmap/pytest.py
- appmap/unittest.py
- pylintrc
These changes also ensure that logging from functions in the `_appmap` module will be emitted. 
Fixes #215 .
> Ensure that functions specified in the config will be recorded

- .flake8
- .travis.yml
- _appmap/test/test_command.py
- _appmap/test/test_django.py
- appmap/flask.py
- pylintrc
- pyproject.toml
- tox.ini
Updates to some dependencies have broken the build on master. These changes make the build green again, and also fix a couple of pylint warnings.
Fixes #237.
> Support Werkzeug v2.3, pin to urllib3 v1

- .travis.yml
- _appmap/importer.py
- pyproject.toml
- requirements-dev.txt
- requirements-test.txt
- tox.ini
These changes ensure that the agent works with 3.12.
Fixes #253 .
> Support python 3.12

- .travis.yml
- _appmap/env.py
- ci/run_tests.sh
- ci/smoketest.sh
- ci/test_pipenv.sh
- ci/test_poetry.sh
- tox.ini
Incorporate fix for logging from @virajkanwade, debug and fix the Travis build.
> Incorporate logging fix, fix the build
