getappmap/appmap-python

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/django.py
- appmap/pytest.py
- appmap/test/test_django.py
The middleware injection is a bit inelegant, but it works pretty well.
#5 wasn't actually blocking this; unittest cases driven by pytest still activate some hooks, just not the one we were using. I've changed the hook to work with them.
Fixes #27.
> HTTP request and response capture in Django

- .travis.yml
- CHANGELOG.md
- README.md
- appmap/_implementation/configuration.py
- appmap/_implementation/env.py
- appmap/_implementation/event.py
- appmap/_implementation/generation.py
- appmap/_implementation/metadata.py
- appmap/_implementation/py_version_check.py
- appmap/_implementation/recording.py
- appmap/_implementation/utils.py
- appmap/django.py
- appmap/pytest.py
- appmap/test/appmap_test_base.py
- appmap/test/conftest.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/data/pytest/expected.appmap.json
- appmap/test/data/pytest/simple.py
- appmap/test/test_metadata.py
- appmap/test/test_recording.py
- conftest.py
- pyproject.toml
- pytest.ini
- tox.ini
Eliminate all uses of features added after Python version 3.5. Add `vermin` to help weed out issues, and `tox` to test against supported versions.
There are also a couple of bug fixes here. I don't love the shenanigans in 6f2a9f1. The problem has proved resistant to my efforts to debug it, though, and the current workaround seems good enough for now. It should probably be revisited sometime soon, though.
> Relax python version requirement to 3.5

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/_implementation/instrument.py
- appmap/_implementation/recording.py
- appmap/test/appmap_test_base.py
- appmap/test/test_configuration.py
- appmap/test/test_recording.py
This should fix a problem where unrelated events end up in test appmaps.
> Clear events list when starting a recording

- CHANGELOG.md
- README.md
- appmap/__init__.py
- appmap/_implementation/event.py
- appmap/_implementation/generation.py
- appmap/_implementation/labels.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/data/pytest/expected.appmap.json
- appmap/test/data/pytest/expected.unittest.appmap.json
- appmap/test/test_labels.py
Provide the `labels` decorator to allow the user to add annotations
(labels) to the classMap entries for functions.
Also, get rid of some code that modified an instrumented function's kwargs. Fixes #61.
> Add appmap.labels decorator

- .travis.yml
- CHANGELOG.md
- README.md
- appmap/_implementation/env.py
- appmap/_implementation/event.py
- appmap/django.py
- appmap/test/data/example_class.py
- appmap/test/test_events.py
- tox.ini
Fixes #68 by adding support for `APPMAP_DISPLAY_PARAMS`.
Fixes #69 by handling HTTP responses that don't have `Content-Type`.
Also, rework the Travis build config so it can cache dependencies. This reduces the build time from 17-20min to ~3min when the cache is available (which it should be for most builds, once this gets merged).
> Add APPMAP_DISPLAY_PARAMS

- CHANGELOG.md
- appmap/_implementation/instrument.py
- appmap/_implementation/recording.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/test_recording.py
- pyproject.toml
Improve handling of multiple calls into a shallow-tracked package. Fixes #72. (I split the changes into two separate commits to make it easier to understand how the expected appmap changed, so it's probably easier to review them individually.)
These changes also switch to using `wrapt` for wrapping the metapath finder functions, which fixes #74. It's currently hard to test the exact environment that reproduces #74, so I'll look at adding a test in a follow-up PR.
Here are some more details for changes to shallow tracking:
Given these functions in a class
```python
@staticmethod
def call_yaml():
return ExampleClass.dump_yaml('ExampleClass.call_yaml')
@staticmethod
def dump_yaml(data):
import io
from yaml import Dumper
stream = io.StringIO()
dumper = Dumper(stream)
try:
dumper.open() …
```
> Reset shallow tracking rule when a function returns

- appmap/pytest.py
Previously used *pytest_runtestloop* stops at first non-*None* result; as a consequence, another plugin (such as *xdist*) might cause skipping our hook. *pytest_sessionstart* doesn't have this problem.
(I ran into this issue when trying to run *saleor* tests with all dev dependencies, including *xdist*, installed. It failed with:
```
@pytest.hookimpl(hookwrapper=True)
def pytest_pyfunc_call(pyfuncitem):
>       with pyfuncitem.session.appmap.record(
pyfuncitem.cls,
pyfuncitem.name,
method_id=pyfuncitem.originalname,
location=pyfuncitem.location):
E               AttributeError: 'Session' object has no attribute 'appmap'
../../.local/lib/python3.9/site-packages/appmap/pytest.py:17: AttributeError
```
.)
> Change pytest session hook to pytest_sessionstart

- CHANGELOG.md
- appmap/django.py
Calling repr() on QuerySet objects in django causes a database query. We don't want these queries to end up in the appmap, since they're not part of the application flow.
Moreover, some tests might record and examine queries using CursorDebugWrapper; we don't want them to see those queries, either.
For an example error caused by this, see https://github.com/rafalp/Misago/blob/da14e8ef712a77603fdfec8bbff67c526c7d0c5c/misago/core/tests/test_chunk_queryset.py#L29 -- this tests counts queries and it fails if it sees additional query caused by us calling repr() on the QuerySet.
Related to #79 .
> Avoid capturing queries caused by calling repr()

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/test/data/expected.appmap.json
- appmap/test/data/pytest/expected.appmap.json
- appmap/test/data/unittest/expected.appmap.json
- appmap/test/test_django.py
- appmap/test/test_params.py
`repr()` is usually the preferred programmer-friendly way to display an object. `str()` is a user representation (for many different meanings of a user), and as such can sometimes cause an expensive and state-changing stringification.
As an example for how that might be harmful, consider `misago.users.admin.forms.EditUserForm.Meta.__init__`:
https://github.com/rafalp/Misago/blob/da14e8ef712a77603fdfec8bbff67c526c7d0c5c/misago/users/admin/forms.py#L202
This method first delegates to superclass, then calls `profilefields.add_fields_to_admin_form(self.request, self.instance, self)`; `self` here is the form. If the appmap hook tries to use `str()` for stringification of this `form` parameter, this will cause HTML rendering and, before that, form validation. Note this happens before the form …
> Use repr() by default for stringification

- CHANGELOG.md
- appmap/flask.py
- appmap/sqlalchemy.py
- appmap/test/test_sqlalchemy.py
- pyproject.toml
SQL queries are captured as long as `appmap.sqlalchemy` is imported before connections are made. Flask integration tries to import it by default, since both are often used in conjunction.
Note captured SQL is parametrized, for example `INSERT INTO users (name, fullname) VALUES (?, ?)`; this is because of how SQLAlchemy executes SQL -- it's actually sent parametrized to the server, the full substituted SQL is never produced outside the database driver (as far as I can tell). This is in line with SQLAlchemy own logging; it adds another line with values:
```
INFO:sqlalchemy.engine.Engine:INSERT INTO users (name, fullname) VALUES (?, ?)
INFO:sqlalchemy.engine.Engine:[generated in 0.00047s] ('jack', 'Jack Jones')
```
Not sure if we should do the same; it can be added to the SQL as a comment, …
> Add SQLAlchemy integration

- README.md
- pyproject.toml
Updating the documentation, the oldest supported version of Python is now 3.6.
> docs: bumping supported python to 3.6+

- .travis.yml
- appmap/_implementation/generation.py
- appmap/_implementation/metadata.py
- appmap/test/normalize.py
- appmap/test/test_metadata.py
- Cache git metadata
This improves performance quite a bit since git doesn't get called several times per test case anymore.
- Streamline metadata tests.
- Skip `status` entry if it would be empty anyway.
> Improve metadata

- CHANGELOG.md
- appmap/_implementation/__init__.py
- appmap/_implementation/metadata.py
- appmap/django.py
- appmap/test/test_django.py
Fixes a problem with Django JSON parameter capture preventing the application from accessing the request body, causing the error:
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
> Use Django cached request body when capturing JSON

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/test/test_params.py
Fixes handling of parameters in two corner cases:
- missing required argument,
- method called with self=None.
The latter caused an error when I was trying to map saleor ([`saleor/graphql/page/tests/test_page_types_sorting_and_filtering.py::test_sort_page_types_by_slug`](https://github.com/mirumee/saleor/blob/master/saleor/graphql/page/tests/test_page_types_sorting_and_filtering.py#L70), for reference).
> Fix params corner cases

- CHANGELOG.md
- appmap/_implementation/event.py
- appmap/test/data/example_class.py
- appmap/test/data/expected.appmap.json
- appmap/test/normalize.py
- appmap/test/test_recording.py
This fixes the problem mentioned in #124 and #80 (functions decorated with lru_cache not having their arguments captured) without actually doing #124. @apotterri, do you remember if there was a specific reason to not follow wrappers? Tests seem to pass fine, I've also ran saleor test suite and everything looks in order.
> Follow wrappers when reflecting for function signature

- CHANGELOG.md
- appmap/_implementation/configuration.py
- appmap/test/test_configuration.py
- pyproject.toml
Resolve the path to `appmap.yml` to an absolute path. This allows the error message for a missing config file to show the expected location of the file.
Fixes #131 .
> Use full path for default appmap.yml

- CHANGELOG.md
- appmap/django.py
- appmap/test/test_django.py
Make path normalization more robust. Instead of trying to duplicate the
functionality of resolve(), we'll call it and interpret the route it
returns.
Fixes #138.
> Make django path normalization more robust

- .gitignore
- .releaserc.yml
- .travis.yml
- appmap/_implementation/configuration.py
- appmap/_implementation/py_version_check.py
- appmap/command/appmap_agent_status.py
- appmap/command/appmap_agent_validate.py
- appmap/test/data/config-exclude/.hide/hidden_mod/__init__.py
- appmap/test/data/config-exclude/node_modules/node_mod/__init__.py
- appmap/test/data/config-exclude/venv/venv_mod/__init__.py
- appmap/test/test_command.py
- appmap/test/test_configuration.py
- ci/smoketest.sh
- pyproject.toml
Add the appmap-agent-validate command to support the CLI's agent installation.
Also, appmap-agent-init now excludes the current virtual environment installation directory (i.e. `sys.prefix`), as well as directories named `node_modules`.
Finally, add `semantic-release`, so we can stop doing releases manually. Yay!
> Add appmap-agent-validate

- appmap/_implementation/configuration.py
- appmap/test/conftest.py
- appmap/test/test_configuration.py
Make sure to honor the setting (or lack thereof) of the `APPMAP`environment variable when a config file is present. Previously, the simple presence of a valid config file caused recording to be enabled.
> fix: Honor APPMAP env var when config is present

- appmap/_implementation/configuration.py
- appmap/_implementation/event.py
- appmap/_implementation/recording.py
- appmap/test/data/appmap.yml
- appmap/test/data/expected.appmap.json
This change is especially useful for library functions; it's not intended to replace the @labels decorator but instead allow to configure labeling of code outside of the developer control.
Planned followups:
- doc change on the website,
- predefined labels for popular libraries.
> Allow specifying function labels in the config file

- .travis.yml
- appmap/_implementation/recording.py
- appmap/test/data/unittest/expected/pytest.appmap.json
- appmap/test/data/unittest/expected/unittest.appmap.json
- appmap/test/data/unittest/simple/test_simple.py
- appmap/test/test_test_frameworks.py
- appmap/unittest.py
- ci/run_tests.sh
- ci/smoketest.sh
- ci/test_pipenv.sh
- pyproject.toml
If a finder function doesn't have a `__name__` attr, and it's a
`functools.partial`, use its `func.__name__` instead.
> fix: Handle a partial finder function

- appmap/django.py
- ci/smoketest.sh
While I couldn't reproduce it, a user has reported seeing a stack
overflow while processing an SQL query with MySQL and django. It
seems to have been caused by appmap querying for the server version,
which entails another SQL query against the server with MySQL.
Since MySQL backend caches that information, querying it when first
establishing the connection ensures the additional query is avoided
later at runtime, thus avoiding this problem.
Fixes #158
> fix: Avoid querying database version when executing client queries

- appmap/test/data/example_class.py
- appmap/test/test_recording.py
- pyproject.toml
- tox.ini
Update our vendored copy of wrapt to include https://github.com/getappmap/wrapt/commit/fb8fc6c1ac75c6dad4642239f737de39be6632c2 . This fixes a problem that occurred when attempting to call `deepcopy` on an instrumented function.
These changes also fix problems when attempting to map Django projects. These problems originally looked like they were related to Django 4. It turns out that they occurred in any project using `django_filter`, e.g. [saleor](https://github.com/saleor/saleor), regardless of Django version.
The tox test matrix has now been updated to include Django 4, so.... Fixes getappmap/board#160.
> Enable instrumented functions to be deepcopy'ed

- appmap/_implementation/event.py
- appmap/_implementation/generation.py
- appmap/_implementation/testing_framework.py
- appmap/pytest.py
- appmap/test/data/expected.appmap.json
- appmap/test/data/pytest/expected/pytest.appmap.json
- appmap/test/data/remote.appmap.json
- appmap/test/data/trial/expected/pytest.appmap.json
- appmap/test/data/unittest/expected/pytest.appmap.json
- appmap/test/data/unittest/expected/unittest.appmap.json
- appmap/test/test_params.py
- appmap/unittest.py
Increased version from 1.4 to 1.9.0
- `metadata.recorder.type` made available in 1.9.0 is now added.
- `size` made available in 1.7.0 (recommended) is now added.
Fields > 1.4 that already existed:
- `test_status` made available in 1.6.0 is already emitted.
- http response and request headers made available in 1.6.0 are already emitted.
- `normalized_path_info` made available in 1.5.1 is already emitted.
- `http_client_request` and `http_client_response` made available in 1.5.0 are already emitted.
Not emitted or not addressed:
- `eventUpdates` were not added, made available in 1.8.0.  Also missing in `appmap-ruby`
- `exception`'s `path` and  `lineno` made available in 1.6.0.  Also missing in `appmap-ruby`
> feat: Update appmap format from 1.4 to 1.9.0

- appmap/_implementation/configuration.py
- appmap/test/test_configuration.py
Create `appmap.yml` if it doesn't exist, and don't create if appmap is disabled.
Fixes https://github.com/getappmap/appmap-python/issues/169
> feat: Create appmap.yml if it doesn't exist

- README.md
- appmap/_implementation/env.py
- appmap/_implementation/testing_framework.py
- appmap/_implementation/utils.py
- appmap/_implementation/web_framework.py
- appmap/django.py
- appmap/flask.py
- appmap/test/conftest.py
- appmap/test/data/django/app/settings.py
- appmap/test/data/django/manage.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
- appmap/test/test_test_frameworks.py
- appmap/test/test_util.py
- appmap/test/web_framework.py
- pytest.ini
Save a separate AppMap file per request.
- If both `APPMAP=true` and `APPMAP_RECORD_REQUESTS=true` then each request is recorded in a separate AppMap file.
- If both remote recording and requests recording are enabled, unique events are created and stored in each recorder.
- To test, an actual Django and Flask server process are started in the background.
This is similar to https://github.com/getappmap/appmap-ruby/pull/273
Fixes https://github.com/getappmap/appmap-python/issues/167
Depends on https://github.com/getappmap/appmap-python/pull/171
> feat: Save an AppMap per request (record_requests)

- pyproject.toml
Some packages that use appmap-python, like saleor, require PyYAML==6.0 and this conflicts with appmap-python requiring 5.3.0.
Fixes https://github.com/getappmap/appmap-python/issues/163
> fix: Require PyYAML >=5.3.0 rather than ^5.3.0

- appmap.pth
- appmap/_implementation/configuration.py
- appmap/test/test_configuration.py
- ci/run_tests.sh
If the config file is missing a value for `name` or `packages`, use the default value instead.
Fixes #181
> fix: use default values when config is incomplete

- appmap/__init__.py
- appmap/_implementation/__init__.py
- appmap/_implementation/configuration.py
- appmap/_implementation/detect_enabled.py
- appmap/_implementation/env.py
- appmap/_implementation/testing_framework.py
- appmap/_implementation/web_framework.py
- appmap/test/test_detect_enabled.py
- appmap/test/test_django.py
- appmap/test/test_test_frameworks.py
- appmap/unittest.py
Don't show noise in the console.
- Show a warning when the agent does something I'm not necessarily expecting, or when I've made a mistake. So, if set `APPMAP=true`, or `APPMAP=false`, or one of the `APPMAP_RECORD_` variables is set to true or false, log at `info`.
- If any of those variables is set to a value other than `true` or `false`, write a message at `warning`. This is new behavior.
- Make the comparison with `true` or `false` be case-insensitive. Before it was done with `== "true"` and `== "false"`.
- If there's an environment variable that starts with the prefix `APPMAP_RECORD_` but doesn't match one of the supported recording types, log a message at `warning`.  This is also new behavior.
- We've gone back and forth about what level to use when recording by default. On balance, …
> feat: downgrade logging level when AppMap recording is enabled

- .travis.yml
- appmap/_implementation/event.py
- appmap/test/data/appmap.yml
- appmap/test/data/appmap_testing/django_simplelazyobject.py
- appmap/test/test_django_simplelazyobject.py
- appmap/test/test_events.py
- ci/deploy.sh
- pylintrc
- pyproject.toml
- tox.ini
The described value could overload `__class__` to something which causes side effects.
This was the cause of the problem found by @symwell in https://github.com/getappmap/appmap-python/issues/165?notification_referrer_id=NT_kwDOAAyRVLE0NDI4ODc3ODA4OjgyMzYzNg#issuecomment-1295264871
> fix: Avoid calling __class__ when describing values

- appmap/_implementation/__init__.py
- appmap/_implementation/configuration.py
- appmap/_implementation/django.py
- appmap/_implementation/env.py
- appmap/_implementation/event.py
- appmap/_implementation/flask.py
- appmap/_implementation/importer.py
- appmap/_implementation/instrument.py
- appmap/_implementation/recorder.py
- appmap/_implementation/remote_recording.py
- appmap/_implementation/web_framework.py
- appmap/django.py
- appmap/flask.py
- appmap/test/test_django.py
- appmap/test/test_flask.py
- appmap/test/test_recording.py
- appmap/test/web_framework.py
- pylintrc
- tox.ini
With these changes, remote recording and per-request recording no longer
interfere with one another.
Fixes getappmap/board#203.
> Remote and requests 20221026

- appmap/command/appmap_agent_init.py
- appmap/command/appmap_agent_status.py
- appmap/command/appmap_agent_validate.py
- ci/smoketest.sh
Add `if __name__ == "__main__"` to the installer scripts so they can be run with `python -m`.
This is needed to support getappmap/appmap-js#840 .
> fix: allow scripts to be run with -m

- appmap/test/test_recording.py
Fixes #200.
The `multiprocessing` modules requires that the callable passed to it be pickleable. Prior to these changes, passing it an instrumented function would fail with the error described in #200.
The fix for this problem is in https://github.com/getappmap/wrapt/commit/7dcec8118747b8a480c1664cad3c16ab9e86f538 . That change updates the `__reduce_ex__` method of `FunctionWrapper` so it just returns the fully-qualified name of the wrapped function. This is enough to enable the function to be pickled and unpickled, as demonstrated by the test in this PR.
You can see the failing behavior in [a previous build](https://app.travis-ci.com/github/getappmap/appmap-python/builds/258568455).
> fix: make sure FunctionWrappers can be pickled

- appmap/test/data/unittest/simple/test_simple.py
- appmap/test/test_test_frameworks.py
- appmap/unittest.py
Make sure unittest integration can handle subtests.
Fixes #206.
> fix: don't fail on unittest subtests

- _appmap/configuration.py
- _appmap/importer.py
- _appmap/test/test_labels.py
Prior to these changes, labeling a module function by a preset would also cause the members of classes in that module to be labeled. For example, the preset label for hmac.create_digest would cause the member functions of hmac.HMAC to be instrumented as well.
Fixes #220.
> fix: don't instrument extra class members

- _appmap/recorder.py
- _appmap/test/data/expected.appmap.json
- appmap/labeling/django.yml
- appmap/labeling/flask.yml
- appmap/labeling/formats.yml
- appmap/labeling/jwt.yml
- appmap/labeling/logger.yml
- appmap/labeling/random.yml
Add label definitions for Python.
Didn't see these labels added in generated AppMaps when I run the tests for an app.  I imagine it's because labels depend on https://github.com/getappmap/appmap-python/pull/218.
- `_appmap/test/data/expected.appmap.json` was changed because `poetry run pytest -v _appmap/test/test_recording.py` didn't pass without this change. Changed by saving at indent=2.
```
file_write("/tmp/generated", json.dumps(remove_line_numbers(generated_appmap), indent=2))
```
- On Django, didn't set anything related to `is_active`, `is_staff`, `is_superuser` because these seem to be fields instead of functions.
Fixes https://github.com/getappmap/appmap-python/issues/214
Depends on https://github.com/getappmap/appmap-python/issues/216
> feat: Add label definitions

- _appmap/importer.py
- _appmap/test/data/django/app/urls.py
- _appmap/test/data/flask/app.py
- _appmap/test/test_command.py
- _appmap/test/test_django.py
- _appmap/test/test_events.py
- _appmap/test/test_flask.py
- _appmap/test/test_metadata.py
- _appmap/test/test_params.py
- _appmap/test/web_framework.py
- _appmap/utils.py
- appmap/django.py
- pylintrc
- pyproject.toml
- tox.ini
Fix the way path normalization is done for Django http_server_requests. Get rid of the use of private functions (which didn't work in all cases), stick to the public API of ResolverMatch.
Fixes #227
> fix: improve Django path normalization

- _appmap/event.py
- _appmap/test/test_describe_value.py
- _appmap/test/test_events.py
- _appmap/test/test_params.py
- _appmap/web_framework.py
Add "properties" and "items" schemas to "parameters" objects , as specified in v1.11.0 of the appmap spec.
Fixes #226 .
> feat: add schema to event parameters

- _appmap/env.py
- _appmap/test/test_django.py
- _appmap/test/test_env.py
- _appmap/test/test_flask.py
- _appmap/testing_framework.py
> fix: Don't record requests in test cases

- .gitmodules
- .travis.yml
- README.md
- _appmap/importer.py
- _appmap/test/data/unittest/expected/pytest.appmap.json
- _appmap/test/data/unittest/expected/unittest.appmap.json
- _appmap/test/data/unittest/simple/test_simple.py
- _appmap/test/test_labels.py
- _appmap/test/test_params.py
- _appmap/test/test_recording.py
- _appmap/test/test_test_frameworks.py
- _appmap/unittest.py
- _appmap/wrapt
- appmap/flask.py
- appmap/pytest.py
- appmap/unittest.py
- appmap/wrapt
- ci/run_tests.sh
- ci/smoketest.sh
- pyproject.toml
- tox.ini
- vendor/_appmap/wrapt/LICENSE
- vendor/_appmap/wrapt/__init__.py
- vendor/_appmap/wrapt/arguments.py
- vendor/_appmap/wrapt/decorators.py
- vendor/_appmap/wrapt/importer.py
- vendor/_appmap/wrapt/wrappers.py
- vendor/patches/wrapt.patch
- vendor/vendor.txt
**Please don't merge this, it needs a rebase**
Fixes #236.
> Support python 3.11

- .travis.yml
- _appmap/test/data/pytest/expected/status_errored.metadata.json
- _appmap/test/data/pytest/expected/status_failed.metadata.json
- _appmap/test/data/pytest/expected/status_xfailed.metadata.json
- _appmap/test/data/unittest/expected/status_errored.metadata.json
- _appmap/test/data/unittest/expected/status_failed.metadata.json
- _appmap/test/data/unittest/expected/status_xfailed.metadata.json
- _appmap/testing_framework.py
> feat: Report test_failure when a test fails

- _appmap/importer.py
- _appmap/test/conftest.py
- _appmap/test/data/appmap-exclude-fn.yml
- _appmap/test/data/appmap-no-pyyaml.yml
- _appmap/test/test_importer.py
- _appmap/test/test_labels.py
Changes in 68ff82e meant that it was no longer possible to exclude a function by name. These changes make it work again.
Fixes #262.
> fix: make sure functions can be excluded

- _appmap/noappmap.py
- _appmap/test/data/pytest/test_noappmap.py
- _appmap/test/data/unittest/expected/pytest.appmap.json
- _appmap/test/data/unittest/expected/status_errored.metadata.json
- _appmap/test/data/unittest/expected/status_failed.metadata.json
- _appmap/test/data/unittest/expected/status_xfailed.metadata.json
- _appmap/test/data/unittest/expected/unittest.appmap.json
- _appmap/test/data/unittest/simple/test_noappmap.py
- _appmap/test/data/unittest/simple/test_simple.py
- _appmap/test/test_test_frameworks.py
- _appmap/unittest.py
- appmap/__init__.py
- appmap/pytest.py
Add appmap.noappmap, to allow the user to disable recording of particular pytest and unittest tests.
Fixes #254 .
Fixes #255 .
> add noappmap decorator

- _appmap/test/data/pytest/expected/pytest.appmap.json
- _appmap/test/data/trial/expected/pytest.appmap.json
- _appmap/test/data/unittest/expected/pytest.appmap.json
- _appmap/test/data/unittest/expected/unittest.appmap.json
- _appmap/testing_framework.py
Correct the position of source_location in an AppMap. It should be a property of metadata, rather than metadata.recording.
Fixes #261.
> move source_location property to metadata

- _appmap/env.py
https://github.com/getappmap/appmap-python/issues/251#issuecomment-1936762922
> Replace logging.info with logger in env.py

- _appmap/env.py
Don't create a log file by default until it's a bit better managed.
> fix: don't create a log file by default

- _appmap/env.py
- _appmap/recording.py
- _appmap/test/conftest.py
- _appmap/test/test_configuration.py
- _appmap/test/test_django.py
- _appmap/test/test_env.py
- _appmap/test/test_fastapi.py
- _appmap/test/test_flask.py
- _appmap/test/test_runner.py
- _appmap/test/test_sqlalchemy.py
- _appmap/test/test_test_frameworks.py
- _appmap/unittest.py
- _appmap/web_framework.py
- appmap/__init__.py
- appmap/command/runner.py
- appmap/fastapi.py
- appmap/pytest.py
- ci/smoketest.sh
- doc/recording-env-vars.md
- pyproject.toml
- tox.ini
**https://github.com/getappmap/applandinc.github.io/pull/1325 needs to be merged before this.**
These change begin the transition of a change in the agent's behavior. In version 2.0 (the next version released), instrumentation will no longer be automatically enabled after it's installed in a Python environment. To create recordings, the environment variable `APPMAP` must be set to `true` (case-insensitive).
In addition, there is now a runner script, `appmap-python`. It can be used to control the environment variables, including `APPMAP_DISABLE_LOG_FILE`.
Fixes #294 .
> feat: don't record by default, add runner

- _appmap/configuration.py
- _appmap/env.py
- _appmap/test/data/config-up/appmap.yml
- _appmap/test/test_configuration.py
- _appmap/test/test_util.py
- _appmap/utils.py
Fixes #295.
- In `Config._load_config`, if the config file is not found relative to the current folder (more precisely `Env.current.root_dir`) it is searched up to the repo root, or up to the file system root if there is no repo.
- `appmap_dir` is resolved relative to the location of config file and `Env.current.output_dir` is updated with this value, unless `APPMAP_OUTPUT_DIR` is set by tests.
- [Tests](https://github.com/getappmap/appmap-python/blob/4d0a29c761850b3320d67a0dfe86dca7b721aee2/_appmap/test/test_configuration.py#L263-L291) added to ensure:
-- Config file is found in a parent folder.
-- Config file is not found up until the repo root even if it exists in the parent directory of the repo root.
-- Config file is not found up until the file system root.
> feat: Search for config file

- _appmap/test/test_sqlalchemy.py
- appmap/sqlalchemy.py
- pyproject.toml
- requirements-dev.txt
- requirements-test.txt
- tox.ini
Fixes #279.
- Fixed deprecated usages in tests. 
-- Passing a string to `Conneciton.execute()` is deprecated in SQLAlchemy 1.4 and removed in 2.0: https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Connection.execute
-- Changed the tests with warnings issuing a DML with `Connection.execute()` to be explicit about commit behavior since auto-commit behavior is changed in 2.0: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
- Updated tox config to test with both 1.4 and 2.0 versions of SQLAlchemy.
> fix SQLAlchemy deprecated execute param in test

- _appmap/__init__.py
- _appmap/configuration.py
- _appmap/env.py
- _appmap/importer.py
- _appmap/singleton.py
- _appmap/test/data/appmap-all-paths-malformed.yml
- _appmap/test/data/appmap-empty-path.yml
- _appmap/test/data/appmap-malformed-path.yml
- _appmap/test/test_configuration.py
- _appmap/testing_framework.py
- appmap/command/appmap_agent_init.py
- appmap/command/appmap_agent_status.py
Fixes #302
Warning and dropping malformed configuration file package path entries, which cannot be parsed as Python module names: `mod1/mod2`, `mod1\mod2`, `123`, `.`, ` `.
> feat: Check malformed path entries

- README.md
- _appmap/env.py
- _appmap/recording.py
- _appmap/test/test_configuration.py
- _appmap/test/test_django.py
- _appmap/test/test_flask.py
- _appmap/test/test_runner.py
- _appmap/test/test_test_frameworks.py
- _appmap/unittest.py
- _appmap/web_framework.py
- appmap/__init__.py
- appmap/command/runner.py
- appmap/pytest.py
- appmap/unittest.py
- docs/recording-env-vars.md
- tox.ini
The agent no longer records by default. Code must be run with `appmap-python`, or with `APPMAP=true` to create AppMap data files.
Additionally, `APPMAP_RECORD_PYTEST` and `APPMAP_RECORD_UNITTEST` have been replaced by `APPMAP_RECORD_TESTS`. Also, `APPMAP_RECORD_PROCESS` now disables other recording types.
Fixes #299.
Fixes #300.
Fixes #301.
Fixes #307.
> disable recording by default

- _appmap/env.py
- _appmap/generation.py
- appmap/__init__.py
- appmap/command/runner.py
- ci/smoketest.sh
With these changes, the string representation of the object will appear in the AppMap. This works well for `numpy.int64`, for example, but it's possible that it will fail for other types.
This has no tests, as yet, soon to be added in https://github.com/getappmap/appmap-python/pull/310 .
Also, while testing this, I noticed a couple of places where record-by-default was still not disabled properly. These changes address them.
> fix: handle non json serializable types

- _appmap/configuration.py
- ci/smoketest.sh
If mapping is disabled, attempting to load file config won't create a new file. Expect this can happen, and don't crash.
Fixes #323 .
> fix: expect a missing config file

- _appmap/__init__.py
- appmap/__init__.py
- ci/smoketest.sh
Make sure that when we get loaded as a pytest plugin, pytest doesn't try to rewrite our modules. This avoids a warning about being unable to do the rewrite, which will cause test failures if warnings have been promoted to errors (e.g. with warnings.simplefilter("error")).
As far as I can tell, this change doesn't affect our internal tests, and we still get proper error messages when one of our assertions fails. Even if this turns out not be true, though, pytest rewriting is cosmetic only: an assertion failure still raises an exception and the test will fail. It just won't have a pretty message.
Fixes #314 .
> fix: ask pytest not to rewrite our modules

- _appmap/instrument.py
- _appmap/recorder.py
If the environment variable APPMAP_MAX_EVENTS is set, use it to limit the number of events added to a Recorder. This setting is a suggestion, rather than a hard limit, but the Recorder should get close.
Fixes #329 .
In the interest of getting this out ASAP, it doesn't have any additional tests. It shouldn't have any impact when it's unset, which is shown by the fact that all the existing tests pass.
> fix: optionally limit number of events collected

- _appmap/recording.py
- appmap/__init__.py
- ci/smoketest.sh
Fixes #326.
- Adds `NoopRecording` class with the same interface as `Recording`.
- Exports `NoopRecording` as `Recording` when `APPMAP` is not set to `true` to prevent "ImportError: cannot import name 'Recording' from 'appmap' ..." in client code.
- Extends [`smoketest.sh`](https://github.com/getappmap/appmap-python/blob/325a58b7981f7e994626b29193ba89e4814bc8d4/ci/smoketest.sh#L31-L48) to ensure that client code using `appmap.Recording` does not fail when `APPMAP=false`.
> fix: appmap.Recording is available even when APPMAP=false

- _appmap/recorder.py
It's possible that when adding an event to the global recorder, the current thread will try to add another event. This happens in Django's tests, because it uses weak references with instrumented finalizers. Calling _add_event can cause the weak reference to get garbage collected, resulting in a call to the finalizer, which will also call _add_event.
Fixes #333 .
> fix: use an RLock in SharedRecorder._add_event

- _appmap/event.py
- _appmap/instrument.py
- _appmap/test/data/example_class.py
- _appmap/test/test_events.py
Fixes #321.
- Disables recording while executing`event.py::describe_value.`
- Prevents "Fatal Python error: Cannot recover from stack overflow." in [sympy](https://github.com/sympy/sympy) project while running tests with AppMap. This problem occurs while describing the `return_value` since describing `Param`s are already protected by `recording_disabled` [here](https://github.com/getappmap/appmap-python/blob/faaf14843448b3f1159246d3866ff3b0df150aed/_appmap/instrument.py#L86).
- Adds a test to ensure that calling instrumented methods as a side effect of describing the return value does not produce additional events.
> fix: max recursion depth exceeded

- _appmap/event.py
- _appmap/instrument.py
- _appmap/recorder.py
- vendor/_appmap/wrapt/wrappers.py
Add `APPMAP_MAX_TIME` which allows the user to specify, in seconds, the maximum time a recording session should be allowed.
In addition, disable rendering of the schema associated with values (parameter, return types) when `APPMAP_DISPLAY_PARAMS=false`.
Finally, move the implementation of `__reduce_ex__` from `wrapt.wrappers.FunctionWrapper` up to `ObjectProxy`. Our implementation, which is good enough for generating AppMaps, works for any instance of an ObjectProxy.
> Add APPMAP_MAX_TIME

- _appmap/env.py
- ci/readonly-mount-appmap.log
- ci/run_tests.sh
- ci/smoketest.sh
Fixes #339.
- Tolerates the inability to create the `appmap.log` file for logging, since a file system read-only error can occur in the [VSCode Python Extension, Virtual Environment, REPL, Shift Enter] scenario when attempting to create the log file.
- Mounts a read-only `appmap.log` file to Docker and adds a test to the smoke test suite for running with a non-modifiable `appmap.log`.
> fix: appmap breaks vscode python extension starting a REPL

- _appmap/test/data/django/test/test_unittest_setup.py
- _appmap/test/test_django.py
- _appmap/unittest.py
Fixes #332
- Hooks `unittest` `TestCase._callSetUp` method to disable request recording in order to prevent the creation of a request recording when a request is made inside `setUp` method of a `unittest` test.
- Adds a `unittest` test to `django` fixture project which makes a request inside `setUp` method. This test makes the `test_django.py::TestDjangoApp::test_enabled` pass with the fix and fail without the fix.
- This edge case can be observed in this test in `django` project:
`$ APPMAP=TRUE ./runtests.py auth_tests.test_views.ChangelistTests.test_user_change_email`
A request made inside `ChangelistTests.setUp` method leads to the creation of requests recording AppMap without the fix.
> fix: request recording in unittest setUp method

- _appmap/event.py
- _appmap/importer.py
- _appmap/test/data/example_class.py
- _appmap/test/test_params.py
- _appmap/test/test_properties.py
- _appmap/utils.py
Any class function decorated with @property, or any class attribute with a property as a value, will now be instrumented.
Fixes #343 .
> feat: instrument properties

- _appmap/env.py
- _appmap/event.py
- _appmap/importer.py
- _appmap/recorder.py
- _appmap/test/conftest.py
- _appmap/test/data/flask-instrumented/appmap.yml
- _appmap/test/data/flask-instrumented/flaskapp.py
- _appmap/test/data/flask-instrumented/init/sitecustomize.py
- _appmap/test/data/flask-instrumented/test_app.py
- _appmap/test/data/flask/flaskapp.py
- _appmap/test/helpers.py
- _appmap/test/test_command.py
- _appmap/test/test_configuration.py
- _appmap/test/test_django.py
- _appmap/test/test_django_simplelazyobject.py
- _appmap/test/test_events.py
- _appmap/test/test_fastapi.py
- _appmap/test/test_flask.py
- _appmap/test/test_params.py
- _appmap/test/test_recording.py
- _appmap/test/test_test_frameworks.py
- _appmap/test/web_framework.py
- _appmap/web_framework.py
- appmap/django.py
- appmap/fastapi.py
- appmap/flask.py
- pylintrc
- pyproject.toml
- pytest.ini
- tox.ini
Currently, if the config specifies that `flask` should be instrumented, an `http_server_response` event gets recorded between the `call` and `return` events for `Flask` functions. Also, a `return` event with an exception will get recorded between the `call` and `return` events for different `Flask`.
These changes hook `finalize_request` and `handle_user_exception`, and ensuring that the events get ordered correctly.
Fixes #341
> fix: Flask event ordering

- _appmap/instrument.py
- _appmap/test/data/example_class.py
- _appmap/test/data/pytest-instrumented/appmap.yml
- _appmap/test/data/pytest-instrumented/init/sitecustomize.py
- _appmap/test/data/pytest-instrumented/test_instrumented.py
- _appmap/test/helpers.py
- _appmap/test/test_events.py
- _appmap/test/test_test_frameworks.py
- Catching `Exception` in the `instrument.py::call_instrumented` function to create exception return event, does not catch the `Skipped` exception raised from the `pytest.skip` function when the `pytest` library is instrumented because the `Skipped` exception is derived from `BaseException` but not from `Exception`. This leads to the bad AppMap due to the missing return event for the instrumented `pytest.skip` function.
- This fixes the problem by catching `BaseException`, the root class of the exception hierarchy, in `call_instrumented` function to be able to create the exception return event even if the instrumented function raises an exception not derived from the `Exception` class.
- Adds a test that records a method raising a `BaseException` which fails with producing a bad AppMap …
> fix: bad appmaps in pytest project tests

- _appmap/importer.py
- _appmap/test/test_properties.py
Disable property instrumentation until it works properly for Django.
> fix: disable property instrumentation by default

- _appmap/event.py
- _appmap/importer.py
- _appmap/instrument.py
- _appmap/test/data/appmap.yml
- _appmap/test/data/example_class.py
- _appmap/test/data/properties_class.py
- _appmap/test/test_params.py
- _appmap/test/test_properties.py
- _appmap/utils.py
- appmap/fastapi.py
- pylintrc
Have APPMAP_INSTRUMENT_PROPERTIES default to true once again.
Special-case properties that have operator.attrgetter as their getter. Django uses this pattern extensively, and this special-case fixes some failures when trying to generate AppMap data for Django tests.
Also, make sure that examining a `partial` that's being used as a static method doesn't crash.
Fixes #357.
Fixes #320 .
> fix: reenable instrumentation of properties

- README.md
- _appmap/env.py
- _appmap/test/conftest.py
- _appmap/test/test_events.py
- appmap/__init__.py
- tox.ini
By default, parameters will no longer be rendered as strings by default.
To see the values of parameters, APPMAP_DISPLAY_PARAMS must be set to
"true".
Fixes #360.
> disable parameter rendering by default

- _appmap/recording.py
This pull request addresses an issue where AppMap data output via process recordings could potentially clobber each other if multiple processes quit within the same second. 
- The file name for AppMap data output now includes the process ID to prevent overwriting data when multiple processes finish execution simultaneously.
These changes ensure that each process's recordings are distinctly named, thereby avoiding data loss due to file overwriting.
> fix: Prevent process recordings from clobbering one another

- tox.ini
Attaching notes on the run, including test errors.
We should also see these in CI
Fixes https://github.com/getappmap/appmap-python/issues/373
Looks like this is still running on Travis -- https://app.travis-ci.com/github/getappmap/appmap-python/builds/273589597
Looks like the build matrix passed with Python >= 3.10. Django 5 is not supported with earlier Pythons, so that is probably why those tests failed. I'm sure Navie can help me figure out how to disable the Django5 tests with those older Pythons.
https://app.travis-ci.com/github/getappmap/appmap-python/builds/273589597
> ci: Update tox configuration to run Django5
